[package]
name = "hello"
version = "0.1.0"
authors = ["John Wiegley <johnw@newartisans.com>"]
edition = "2018"

[lib]
name = "rust"
crate-type = ["staticlib"] # could be `staticlib` as well

[dependencies]
